.TH ELM-SERVER "1" "June 2014" "elm-server 0.11" "User Commands"
.SH NAME
elm-server \- Server that lets you quickly reload Elm projects in your browser
.SH DESCRIPTION
Elm Server 0.11, (c) Evan Czaplicki 2011\-2014
.SH SYNOPSIS
elm-server flags [OPTIONS]
.IP
Quickly reload Elm projects in your browser. Just refresh to recompile. It
serves static files and freshly recompiled Elm files.
.SS "Common flags:"
.TP
\fB\-p\fR \fB\-\-port\fR=\fIINT\fR
set the port of the server
.TP
\fB\-r\fR \fB\-\-runtime\fR=\fIFILE\fR
Specify a custom location for Elm's runtime system.
.TP
\fB\-h\fR \fB\-\-help\fR
Display help message
.TP
\fB\-v\fR \fB\-\-version\fR
Print version information
